// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AMap: typeof import('./src/components/aMap.vue')['default']
    AsyncChildren: typeof import('./src/components/asyncChildren.vue')['default']
    AsyncChildren2: typeof import('./src/components/asyncChildren2.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotTest: typeof import('./src/components/slotTest.vue')['default']
    TreeChildren: typeof import('./src/components/treeComponent/treeChildren.vue')['default']
    TreeComponentTest: typeof import('./src/components/treeComponent/treeComponentTest.vue')['default']
  }
}
