// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Affix: typeof import('./src/components/Affix/affix.vue')['default']
    AffixComponent: typeof import('./src/components/Affix/affix-component.vue')['default']
    AMap: typeof import('./src/components/map/aMap.vue')['default']
    AsyncChildren: typeof import('./src/components/asyncChildren.vue')['default']
    AsyncChildren2: typeof import('./src/components/asyncChildren2.vue')['default']
    Dynamic: typeof import('./src/components/slot/dynamic.vue')['default']
    Editor: typeof import('./src/components/editor/editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Father: typeof import('./src/components/test/father.vue')['default']
    InfiniteScroll: typeof import('./src/components/infiniteScroll/infiniteScroll.vue')['default']
    Lazy: typeof import('./src/components/lazy/lazy.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    Modifier: typeof import('./src/components/modifier/Modifier.vue')['default']
    ModifierComponent: typeof import('./src/components/modifier/ModifierComponent.vue')['default']
    MyInput: typeof import('./src/components/packaging/my-input.vue')['default']
    PackagingEle: typeof import('./src/components/packaging/packaging-ele.vue')['default']
    RefComponent: typeof import('./src/components/refAndReactive/ref-component.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slot: typeof import('./src/components/slot/slot.vue')['default']
    SlotContent: typeof import('./src/components/slot-slotted/slot-content.vue')['default']
    Slotted: typeof import('./src/components/slot-slotted/slotted.vue')['default']
    Son: typeof import('./src/components/test/son.vue')['default']
    Table: typeof import('./src/components/table/table.vue')['default']
    TableSafe: typeof import('./src/components/slot/table-safe.vue')['default']
    Transfer: typeof import('./src/components/Transfer/Transfer.vue')['default']
    TransferComponent: typeof import('./src/components/Transfer/transfer-component.vue')['default']
    TreeChildren: typeof import('./src/components/treeComponent/treeChildren.vue')['default']
    TreeComponentTest: typeof import('./src/components/treeComponent/treeComponentTest.vue')['default']
    TreeFather: typeof import('./src/components/treeComponent/treeFather.vue')['default']
    TreeOption: typeof import('./src/components/treeComponent/treeOption.vue')['default']
    TsxComponent: typeof import('./src/components/tsx/tsxComponent.vue')['default']
    WatchOption: typeof import('./src/components/watch/watch-option.vue')['default']
  }
}
