// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Affix: typeof import('./src/components/Affix/affix.vue')['default']
    AffixComponent: typeof import('./src/components/Affix/affix-component.vue')['default']
    AMap: typeof import('./src/components/map/aMap.vue')['default']
    AsyncChildren: typeof import('./src/components/asyncChildren.vue')['default']
    AsyncChildren2: typeof import('./src/components/asyncChildren2.vue')['default']
    Date: typeof import('./src/components/date/date.vue')['default']
    DateCompoent: typeof import('./src/components/date/date-compoent.vue')['default']
    DateComponent: typeof import('./src/components/date/date-component.vue')['default']
    Dynamic: typeof import('./src/components/slot/dynamic.vue')['default']
    Editor: typeof import('./src/components/editor/editor.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Father: typeof import('./src/components/test/father.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slot: typeof import('./src/components/slot/slot.vue')['default']
    Son: typeof import('./src/components/test/son.vue')['default']
    TableSafe: typeof import('./src/components/slot/table-safe.vue')['default']
    TreeChildren: typeof import('./src/components/treeComponent/treeChildren.vue')['default']
    TreeComponentTest: typeof import('./src/components/treeComponent/treeComponentTest.vue')['default']
    TreeFather: typeof import('./src/components/treeComponent/treeFather.vue')['default']
    TreeOption: typeof import('./src/components/treeComponent/treeOption.vue')['default']
  }
}
