// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AMap: typeof import('./components/map/aMap.vue')['default']
    AsyncChildren: typeof import('./components/asyncChildren.vue')['default']
    AsyncChildren2: typeof import('./components/asyncChildren2.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Father: typeof import('./components/test/father.vue')['default']
    Map: typeof import('./components/map.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotTest: typeof import('./components/slot/slotTest.vue')['default']
    Son: typeof import('./components/test/son.vue')['default']
    TreeChildren: typeof import('./components/treeComponent/treeChildren.vue')['default']
    TreeComponentTest: typeof import('./components/treeComponent/treeComponentTest.vue')['default']
    TreeFather: typeof import('./components/treeComponent/treeFather.vue')['default']
    TreeOption: typeof import('./components/treeComponent/treeOption.vue')['default']
  }
}
